version: '3'
services:
  database:
    container_name: $POSTGRES_HOST
    image: postgres:10.5-alpine
    ports:
      - $POSTGRES_PORT:5432
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    volumes:
      - ./data:/var/lib/postgresql/data

  server:
    restart: always
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      # DB
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_HOST=$POSTGRES_HOST
      - POSTGRES_PORT=$POSTGRES_PORT
      # FLASK
      - FLASK_ENV=$FLASK_ENV
      - FLASK_APP=$FLASK_APP
      - FLASK_HOST=$FLASK_HOST
    ports:
      - $FLASK_PORT:$FLASK_PORT
    volumes:
      - ./server:/usr/src/

  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - './client:/app'
      - '/app/node_modules'
    ports:
      - '3000:3000'
    depends_on:
      - 'server'
