version: "3"
services:
  db:
    image: postgres:10.5-alpine
    container_name: postgres
    env_file: .env
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    volumes:
      - "./data:/var/lib/postgresql/data"

  server:
    restart: always
    env_file: ./server/.env
    build:
      context: ./server/
      dockerfile: Dockerfile
    command: python manage.py run -h 0.0.0.0
    ports:
      - "5000:5000"
    volumes:
      - ./server:/usr/src/
    depends_on:
      - "db"

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - "./client:/app"
    ports:
      - "3000:3000"
    depends_on:
      - "server"
    # environment:
    #   - NODE_ENV=development
    #   - CHOKIDAR_USEPOLLING=true
    # - HOST_URL=http://192.168.99.100:5000
